name: test-all
on:
  push:
    branches-ignore:
      - 'dependabot/**' #avoid duplicates: only run the PR, not the commit
    tags-ignore:
      - 'v*' #avoids rerun existing commit on release
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3
      - name: Select Java Version
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      # - name: Build and test UT
      #   run: mvn test -Dmaven.test.failure.ignore=true -U --no-transfer-progress
      # Aunque solo los test it que ejecutan swing requieren un display Xvfb, ejecuto todo bajo esta accion
      - name: Buils and run all tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: mvn install -Dmaven.test.failure.ignore=true -U --no-transfer-progress

      - name: Publish surefire test report
        if: always()
        uses: mikepenz/action-junit-report@v3.3.3
        with:
          check_name: test-report
          report_paths: 'target/*-reports/TEST-*.xml'
          fail_on_failure: 'true'
 
      - if: always()
        name: Publish html test reports to an artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-report-files
          path: |
            target/screenshots/
            target/site/

      # Run Sonarqube

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Download sonarscanner
        run: curl --insecure -o ./sonarscanner.zip -L https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip && unzip -q sonarscanner.zip

      - name: SonarQube Analysis
        if: ${{ github.actor != 'dependabot[bot]' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: sonar-scanner-4.7.0.2747-linux/bin/sonar-scanner -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=my:samples-test-java -Dsonar.organization=giis
      - name: SonarQube Quality Gate check
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
